# Generated by Django 2.2 on 2019-04-27 21:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.CharField(max_length=50)),
                ('reference_photo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 4, 27, 21, 41, 0, 35099, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, null=True, verbose_name="Author's name if provided.")),
                ('author_ip', models.CharField(max_length=50, verbose_name="Author's IP.")),
                ('reference_url', models.URLField(verbose_name='URL to the picture in AWSS3')),
                ('alt_description', models.CharField(max_length=50)),
                ('is_aproved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 4, 27, 21, 41, 0, 35696, tzinfo=utc))),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('aproved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Extended user data.')),
            ],
        ),
    ]
