# Generated by Django 2.2 on 2019-04-27 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 21, 41, 19, 483945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 21, 41, 19, 484539, tzinfo=utc)),
        ),
    ]
